version: '3'
services:
  node-api:
    build:
      context: .
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    ports:
      -8000:8000
    command: node dist/index.js