version: '3'
services:
  node-api:
    container_name: node-api-dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:    
      - NODE_ENV=development
      - MONGO_URI=${MONGO_URI}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - SESSION_SECRET=${SESSION_SECRET}
    ports:
      - "8000:8000"
    command: npm run dev

  mongo_db:
    container_name: docker-mongo-dev
